### ISSUE TITLE
photo_search not matching website search

### ISSUE THREAD

**Issue by arw36** [ropensci/photosearcher#5]
Hi, 

I am trying to retrieve photos through the `photo_search` function, but I don't think this is matching the website search. I have an API key, but keep getting 
 ```
Error in photo_search(text = "cacomistle") : 
  No photographs meeting criteria
```
Despite photos appearing online. Let me know if you need more detail. Thanks!

**Comment by Dr-Nathan-Fox** [comment]
Hi,

Sorry for the slow reply. The error you are experiencing is probably due to the `mindate_taken` and `maxdate_taken` fields being defaulted to "2019-01-01". If you set these to a wider search you should get results as expected.

Kindest regards,
Nathan

**Comment by arw36** [comment]
Thanks, that fixed it!
