### ISSUE TITLE
Different metadata via photo_search vs. get_photoinfo

### ISSUE THREAD

**Issue by arw36** [ropensci/photosearcher#7]
Hi, 

This is more of a fundamental questions. Why does different metadata come down for the photo_search and get_photoinfo functions? For some reason, a photo I know should come up in a search (includes keyword in title) doesn't. I was trying to manually append it to be search outputs, but can't pull down the same variables as from the photo_search output. 

```r
photo_search(mindate_taken = "2019-04-15", text = "Pseudocheirus")
get_photoinfo(33827082318)
```
Any help, clarification, would be much appreciated.

**Comment by Dr-Nathan-Fox** [comment]
The photograph seems to come up if you search with the correct maxdate_taken. I was able to return the photograph in question using:

`photo_search(mindate_taken = "2019-04-15", maxdate_taken = "2019-04-28", text = "Pseudocheirus")`

I hope this answers your question.
