### ISSUE TITLE
Hex image not rendered on docs page

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/photosearcher#8]
https://docs.ropensci.org/photosearcher/

but it's ok in your README https://github.com/ropensci/photosearcher

**Comment by jeroen** [comment]
Currently the hex logo is stored in `inst/images`. You need to store figures used by the readme into the `./man/figures` folder. See this comment from Hadley: https://github.com/ropensci/rotemplate/issues/19#issuecomment-506315565

You can also have a look at how other packages include readme figures:

 - https://github.com/ropensci/tidyhydat/
 - https://github.com/ropensci/drake/
